### ISSUE TITLE
IP cannot be accessed

### ISSUE THREAD

**Issue by yuexinlp** [Kaboms/UE-Simple-Http-Server#1]
I'm glad I started a service using it, but I encountered a problem. I can't access it through the IPv4 LAN address. I see that the address in the UE's HttpServerConfig source code is localhost. I'm not sure if this can only bind 127.0.0.1. , have you tried accessing the service address directly via LAN?

**Comment by yuexinlp** [comment]
I found a solution, which needs to be added in the project's Engine configuration file, otherwise it will always bind to 127.0.0.1 by default.

[HTTPServer.Listeners]
DefaultBindAddress=0.0.0.0

**Comment by Kaboms** [comment]
Thank you for using this plugin and giving feedback! I'm glad you find a solution. I'm will add a link to this issue to Readme for anyone who will encounter a same problem.

**Comment by yuexinlp** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
