### ISSUE TITLE
Issues with importing / ue version issue

### ISSUE THREAD

**Issue by StanleyJancha** [Kaboms/UE-Simple-Http-Server#2]
Hello, 
will this work with Unreal engine 5.4.4? If so, I have an issue with importing. After downloading ZIP of this project I extract it to a folder and put it in a folder called "Plugins" in my game directory. I get "The following modules are missing or built with a different engine version: SimpleHttpServer" error.  What could be the issue and how to fix it?

**Comment by CyberAmphibian** [comment]
Hi. Looks like you use blueprints only project. This plugin needs to be compiled from source code manually for UE 5.4.4
I will compile plugin for UE 5.4.4 and publish this for you.

**Comment by Kaboms** [comment]
> Hello, will this work with Unreal engine 5.4.4? If so, I have an issue with importing. After downloading ZIP of this project I extract it to a folder and put it in a folder called "Plugins" in my game directory. I get "The following modules are missing or built with a different engine version: SimpleHttpServer" error. What could be the issue and how to fix it?

Hi. There was a error here for UE 5.4
I'm fixed that and now plugin support UE 5.4
You can get latest release here: https://github.com/Kaboms/UE-Simple-Http-Server/releases/tag/v.1.0
