### ISSUE TITLE
HTTP Server closes constantly

### ISSUE THREAD

**Issue by bencehari** [Kaboms/UE-Simple-Http-Server#3]
Hi @Kaboms,

The plugin is awesome; on UE 5.3, it worked flawlessly, but on 5.4.4, it stops every time.
Running from VS, the output is always something like that:

```
[[2024.11.20-20.38.33:268][106]]LogHttpServerModule: Starting all listeners...
[[2024.11.20-20.38.33:268][106]]LogHttpListener: Created new HttpListener on 127.0.0.1:8080
[[2024.11.20-20.38.33:268][106]]LogHttpServerModule: All listeners started
[[2024.11.20-20.38.33:268][106]]LogTemp: Web server started on port = 8080
[[2024.11.20-20.38.33:268][106]]LogBlueprintUserMessages: [Default_C_2] HTTP Server started on port 8080
[[2024.11.20-20.38.33:276][106]]PIE: Server logged in
[[2024.11.20-20.38.33:277][106]]PIE: Play in editor total start time 0,216 seconds.
[[2024.11.20-20.39.21:162][956]]LogHttpServerModule: Stopping all listeners...
[[2024.11.20-20.39.21:162][956]]LogHttpListener: HttListener stopping listening on Port 8080
[[2024.11.20-20.39.21:162][956]]LogHttpServerModule: All listeners stopped
```

Both in the editor and in the build (Windows).
It doesn't matter if I call endpoints. The time needed for stopping varies.
I tried in an empty project, and the showcase also produced the same result on multiple PCs.

**Comment by Kaboms** [comment]
Hi @bencehari 
Thank you for your feedback.
I'll try to investigate this on UE 5.4

**Comment by Kaboms** [comment]
Looks like I fixed that.
You can find the latest release here: https://github.com/Kaboms/UE-Simple-Http-Server/releases/tag/v.1.1
I'm waiting for your feedback.

**Comment by bencehari** [comment]
@Kaboms you are awesome! It works like a charm :)
